DatastarSamples/Models/AlertViewModel.cs
namespace DatastarSamples.Models;

public record AlertViewModel(string Message, string AlertClass);

DatastarSamples/Models/ErrorViewModel.cs
namespace DatastarSamples.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

DatastarSamples/Models/IndexViewModel.cs
namespace DatastarSamples.Models;

public record IndexViewModel(IEnumerable<Order> Orders);

DatastarSamples/Models/Order.cs
using Bogus;

namespace DatastarSamples.Models;

public class Order
{
    public static string[] Fruits = new[] {"apple", "banana", "orange", "strawberry", "kiwi"};
    public static IEnumerable<Order> SampleOrders;

    static Order()
    {
        var orderIds = 0;
        var testOrders = new Faker<Order>()
            //Ensure all properties have rules. By default, StrictMode is false
            //Set a global policy by using Faker.DefaultStrictMode if you prefer.
            .StrictMode(true)
            //OrderId is deterministic
            .RuleFor(o => o.OrderId, f => orderIds++)
            //Pick some fruit from a basket
            .RuleFor(o => o.Item, f => f.PickRandom(Fruits))
            //A random quantity from 1 to 10
            .RuleFor(o => o.Quantity, f => f.Random.Number(1, 10))
            //A nullable int? with 80% probability of being null.
            //The .OrNull extension is in the Bogus.Extensions namespace.
            .RuleFor(o => o.LotNumber, f => f.Random.Int(0, 100).OrNull(f, .8f));

        SampleOrders = testOrders.Generate(100);
    }
    
    public int OrderId { get; set; }
    public string Item { get; set; }
    public int Quantity { get; set; }
    public int? LotNumber { get; set; }
    
    
}

DatastarSamples/Models/TablePartialViewModel.cs
namespace DatastarSamples.Models;

public record TablePartialViewModel(IEnumerable<Order> Orders);

DatastarSamples/Controllers/HomeController.cs
using System.Diagnostics;
using DatastarSamples.Models;
using DatastarSamples.Extensions;
using Microsoft.AspNetCore.Mvc;
using StarFederation.Datastar.DependencyInjection;

namespace DatastarSamples.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        //show all orders
        var vm = new IndexViewModel(Order.SampleOrders);
        return View(vm);
    }

    [HttpPost("max")]
    public async Task _OrdersTable([FromServices] IDatastarServerSentEventService sse, [FromForm] int maxOrderCount, [FromForm] int delayInSeconds = 0)
    {
        //get first x orders
        if (maxOrderCount < 0)
        {
            var badAlertVm = new AlertViewModel("You can't ask for a negative max order count", "alert-danger");
            await StreamAlert(badAlertVm, sse);
            return;
        }

        string alertMessage;

        if (maxOrderCount > Order.SampleOrders.Count())
        {
            alertMessage = $"There are only {Order.SampleOrders.Count()} sample orders so only those will returned.";
            maxOrderCount = Order.SampleOrders.Count();
        }
        else
        {
            alertMessage = $"[{maxOrderCount}] orders will be returned.";
        }
        
        var alertVm = new AlertViewModel(alertMessage, "alert-info");
        await StreamAlert(alertVm, sse);
        
        if (delayInSeconds is < 0 or > 5)
        {
            delayInSeconds = 5;
        }
        
        await Task.Delay(delayInSeconds * 1000);
        
        IEnumerable<Order> orders = Order.SampleOrders.Take(maxOrderCount);
        var tableVm = new TablePartialViewModel(orders);
        await StreamOrderTable(tableVm, sse);
        
        await StreamAlert(new AlertViewModel("Loading complete", "alert-success"), sse);
    }

    public async Task StreamAlert(AlertViewModel alertViewModel, IDatastarServerSentEventService sse)
    {
        var html = await this.RenderViewToStringAsync("_Alert", alertViewModel);
        await sse.MergeFragmentsAsync(html);
    }

    public async Task StreamOrderTable(TablePartialViewModel tablePartialViewModel, IDatastarServerSentEventService sse)
    {
        var html = await this.RenderViewToStringAsync("_TablePartial", tablePartialViewModel);
        await sse.MergeFragmentsAsync(html);
    }
    
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

DatastarSamples/Controllers/ModalTestController.cs
using DatastarSamples.Extensions;
using Microsoft.AspNetCore.Mvc;
using StarFederation.Datastar.DependencyInjection;

namespace DatastarSamples.Controllers;

public class ModalTestController: Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public async Task ReloadModal([FromServices] IDatastarServerSentEventService sse, bool first)
    {
        var modalContent = await this.RenderViewToStringAsync("_Modal1", first);
        await sse.MergeFragmentsAsync(modalContent);

        if (first)
        {
            await sse.ExecuteScriptAsync("showModal()");
        }
    }

    [HttpPost]
    public async Task Save([FromServices] IDatastarServerSentEventService sse)
    {
        await Task.Delay(200);
        await sse.ExecuteScriptAsync("hideModal()");
        await sse.ExecuteScriptAsync("showSuccessToast()");
    }
}

DatastarSamples/Views/Home/Index.cshtml
@model IndexViewModel
@{
    ViewData["Title"] = "Home Page";
}

<h1 class="display-4 bg-primary-subtle d-flex align-items-center justify-content-center">
    <img src="images/datastarwhitelogo.svg" style="height: 1em;" alt="Datastar white logo"/> Datastar Test
</h1>

<div class="container px-0 py-1" id="featured-3">
    <h2 class="pb-2 border-bottom">Sample Orders</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-2">
        <div class="feature col">
            <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="bi bi-table" viewBox="0 0 16 16">
                    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm15 2h-4v3h4zm0 4h-4v3h4zm0 4h-4v3h3a1 1 0 0 0 1-1zm-5 3v-3H6v3zm-5 0v-3H1v2a1 1 0 0 0 1 1zm-4-4h4V8H1zm0-4h4V4H1zm5-3v3h4V4zm4 4H6v3h4z"/>
                </svg>
            </div>
            <h3 class="fs-2 text-body-emphasis">View the first <em>n</em> orders</h3>
            <p>This demonstrates returning multiple SSE events - an alert and a table</p>
            <form 
                data-signals="{maxOrderCount: 50, delayInSeconds: 3}"
                data-on-submit="@@post('@Url.Action("_OrdersTable")', {contentType: 'form', openWhenHidden: true})">
                <div class="mb-3">
                    <label for="maxNum" class="form-label">Max number of orders</label>
                    <input data-bind="maxOrderCount" type="number" class="form-control" name="maxOrderCount" id="maxNum" aria-describedby="maxNumHelp" min="-1" max="@Order.SampleOrders.Count()">
                    <div id="maxNumHelp" class="form-text">Enter a number between -1 and @Order.SampleOrders.Count()</div>
                </div>
                <div class="mb-3">
                    <label for="delayInSeconds" class="form-label">Delay</label>
                    <input data-bind="delayInSeconds" type="number" class="form-control" name="delayInSeconds" id="delayInSeconds" aria-describedby="delayInSecondsHelp" min="0" max="5">
                    <div id="delayInSecondsHelp" class="form-text">Enter a number of seconds between 0 and 5</div>
                </div>
                <button type="submit" class="btn btn-outline-primary">Submit</button>
            </form>
        </div>
        <div class="feature col">
            <div class="card text-bg-light mb-3">
                <div class="card-header">What this Datastar sample demonstrates:</div>
                <div class="card-body">
                    <h5 class="card-title">Implemented:</h5>
                    <ol>
                        <li>Using the dotnet SDK in an MVC app</li>
                        <li>Sending signals in a form post to the server</li>
                        <li>Sending multiple events from the server in one request</li>
                        <li>Using merge fragments to display an alert</li>
                        <li>Using merge fragments to replace an entire table</li>
                    </ol>
                    <h5 class="card-title">Up next:</h5>
                    <ol>
                        <li>Initializing a 3rd party library, DataTables, with returned fragments using <em>execute-script</em></li>
                        <li>Using <em>data-computed</em> and <em>data-on-interval</em> to show a countdown timer</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="alert">
    
</div>

@await Html.PartialAsync("_TablePartial", new TablePartialViewModel(Model.Orders))

DatastarSamples/Views/Home/_Alert.cshtml
@model AlertViewModel

<div id="alert" class="alert @Model.AlertClass">
    @Model.Message
</div>

DatastarSamples/Views/Home/_TablePartial.cshtml
@model TablePartialViewModel

@{
    Layout = null;
}

<table id="orderTable" class="table table-striped">
    <thead>
    <tr>
        <th>Id</th>
        <th>Item</th>
        <th>Quantity</th>
        <th>Lot Number</th>
    </tr>
    </thead>
    <tbody>
    @if (!Model.Orders.Any())
    {
        <tr>
            <td colspan="4" class="text-center">No orders to display.</td>
        </tr>
    }
    else
    {
        foreach (var order in Model.Orders)
        {
            <tr>
                <td>@order.OrderId</td>
                <td>@order.Item</td>
                <td>@order.Quantity</td>
                <td>@order.LotNumber</td>
            </tr>
        }    
    }
    </tbody>
</table>


DatastarSamples/Views/ModalTest/Index.cshtml
@using Microsoft.VisualBasic
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Modal Tests</h2>


<div class="vstack gap-3">
    <button type="button" class="btn btn-primary" data-on-click="@@get('@Url.Action("ReloadModal", new{ first = true})')">
        Launch demo modal
    </button>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="exampleModalContent">
            </div>
        </div>
    </div>
</div>

<div id="successToast" class="toast align-items-center text-bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
        <div class="toast-body">
            Entity saved.
        </div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
</div>

@section Scripts
{
    <script>
        const modal = new bootstrap.Modal('#exampleModal');

        function showModal(){
            modal.show();
        }

        function hideModal(){
            modal.hide();
        }
        
        const successToast = bootstrap.Toast.getOrCreateInstance('#successToast');
        
        function showSuccessToast(){
            successToast.show();
        }

    </script>    
}

DatastarSamples/Views/ModalTest/_Modal1.cshtml
@model bool
@{
    Layout = null;
}


<div id="exampleModalContent">
    @if (Model)
    {
        <div class="modal-body">
            This is the body of the modal
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-on-click="@@get('@Url.Action("ReloadModal", new {first = false})')">Datastar</button>
        </div>    
    }
    else
    {
        <div class="modal-body">
            This could be step 2 of the same modal. We could also replace the modal header.
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline-danger" data-on-click="@@get('@Url.Action("ReloadModal", new {first = true})')">Back</button>
            <button type="button" class="btn btn-primary" data-on-click="@@post('@Url.Action("Save")')">Save changes</button>
        </div>
    }
    
</div>
      

DatastarSamples/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - DatastarSamples</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/DDatastarSamplestyles.css" asp-append-version="true"/>
    <script type="module" src="https://cdn.jsdelivr.net/gh/starfederation/datastar@1.0.0-beta.7/bundles/datastar.js"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DatastarSamples</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ModalTest" asp-action="Index">Modal Test</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item ms-auto me-2">
                        <a class="nav-link text-dark" href="https://github.com/pholly/DatastarSamples"><i class="bi bi-github"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - DatastarSamples <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>